### ISSUE TITLE
Starting the mock servers will often hang on reload

### ISSUE THREAD

**Issue by paulpdaniels** [apollographql/apollo-workbench-vscode#102]
We have a graph with 14 subgraphs using managed federation. Usually the first run from within the application will properly spin up the local gateway. However when I make changes to one of the subgraphs and try to restart it, it will often hang with no way to stop or restart short of restarting vs code.

<img width="469" alt="Screenshot 2021-07-30 at 2 38 56 PM" src="https://user-images.githubusercontent.com/2528918/127611598-3a25d276-2fc7-4db7-9bc9-2b29f529e6f8.png">

Usually this also results in the local gateway being unavailable for sandbox as well.

**Comment by michael-watson** [comment]
Thanks for reporting this and the picture of the stuck progress indicator, I'm actively looking into this. 

One question I have for you @paulpdaniels is perhaps what type of feedback you might like to see when that "restart" of certain mocked servers happens?

**Comment by paulpdaniels** [comment]
@michael-watson I think just a log message in the console saying something like:

```
Changes detected in subgraph: <>
Restarting subgraph: <>
Recompiling supergraph....Done
```

would probably be enough for me

**Comment by setchy** [comment]
I've been experiencing the same symptoms in our use of Workbench
