### ISSUE TITLE
Apollo workbench in VS Code unresponsive

### ISSUE THREAD

**Issue by kfwerf** [apollographql/apollo-workbench-vscode#112]
Hello from Spotify!

I have been trying to use your tool for splitting schema's but I have had no luck getting it to work. I even tried upgrading to the latest;

Visual Studio Code:

```
Version: 1.60.2 (Universal)
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T11:59:27.195Z (1 day ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

Apollo extensions
```
Apollo GraphQL: v.1.19.6
Apollo Workbench: v1.2.3
```

Nothing is reacting. The plus button is unresponsive, when loading in a workbench from a colleague it cannot find anything. I am not familiar with VS Code that much so unsure how to put it in debug mode, my hunch is the extension in the background is spitting out a lot of errors.

When i try via the Command Palette to Login to Apollo, i get:
`Command 'Apollo Workbench: Login to Apollo' resulted in an error (command 'extension.enterStudioApiKey' not found)`

I hope that gives some clue as to what is happening, I am quite unsure. I checked the other issues and I think this is something standalone. Please advice what I am doing wrong or what I should do.

Thanks,

Kenneth van der Werf

**Comment by michael-watson** [comment]
#115 should have fixed this, apologies for not making that connection. The latest has the login command properly wired up and shouldn't block functionality anymore (that was a bug).
