### ISSUE TITLE
Apollo Workbench file isn't git friendly

### ISSUE THREAD

**Issue by sshevlyagin** [apollographql/apollo-workbench-vscode#113]
It would be nice if the files were multi line so they were easier to manage in github/lab. Currently the workbench file is one line and always get rewritten.

**Comment by michael-watson** [comment]
I think #127 is related

We're investigating pointing at schema files directly (or a rover configuration file) to help with this.

**Comment by bassrock** [comment]
hi @michael-watson Definitely interested in this! We were looking at using Apollo Workbench + Git/GraphQL files locally as an easy way to co-locate our schema design and for folks to review prs of schema updates.

**Comment by michael-watson** [comment]
Workbench now supports the router config files directly and I think this provides a much better `git` experience with local schema files. I do think a Changelog export feature would be nice in the future. I'm going to close this issue for now during a cleanup of the repo. Feel free to re-open this issue or a new one if you have ideas/challenges using the new format for workbench.
