### ISSUE TITLE
Bug: not able to run command: "Apollo Workbench: Login to Apollo"

### ISSUE THREAD

**Issue by dchambers** [apollographql/apollo-workbench-vscode#115]
This is essentially a dupe of #92, but I'm opening a new ticket to hopefully bring it to the attention of the repository owner.

**Comment by kshlyk** [comment]
Have the same issue on v1.2.7 with VS Code 1.61.1. 
MacBook Air (M1, 2020) MacOS Big Sur 11.5.2 (20G95)

**Comment by davidgray-babylon** [comment]
> Have the same issue on v1.2.7 with VS Code 1.61.1. MacBook Air (M1, 2020) MacOS Big Sur 11.5.2 (20G95)
> 
> UPD: Installing the npm has fixed the problem

Thanks @kshlyk - same for me - npm not installed.
The "Developer: show logs" command indicates what's wrong when you try to open the Apollo Workbench extension
<img width="1300" alt="Screenshot 2021-11-02 at 12 10 51" src="https://user-images.githubusercontent.com/56640078/139844952-c512a15e-2d25-4767-876c-ee73a96785c6.png">
.

**Comment by dchambers** [comment]
This also worked for me BTW, so I'm guessing it was `npm` as I now have that installed 😁 . Thanks everyone! 🙇

**Comment by martinmart92** [comment]
I have npm installed and I still get the same error. I do not see logs in my console.  I have tried to reinstall VS Studio and the Apollo Workbench extension a few times without success. 
Any suggestions on how to debug this? I'm happy to provide more logs but I'm not sure where to find them. The "Developer: show logs" didn't contain meaningful error message unfortunately. 

Thanks
