### ISSUE TITLE
Workbench removes path of url after running query from studio

### ISSUE THREAD

**Issue by damienpontifex** [apollographql/apollo-workbench-vscode#126]
I set one of my subgraphs in workbench to this to test a locally running subgraph
```json
{
  "url": "http://localhost:4003/graphql",
  "requiredHeaders": [],
  "mocks": {
    "shouldMock": false,
    "autoUpdateSchemaFromUrl": true
  }
}
```

When the browser launches and I hit Run for the query, the config in VSCode is set back to the below - noting the removal of the `/graphql` path. 
```json
{
  "url": "http://localhost:4003",
  "requiredHeaders": [],
  "mocks": {
    "shouldMock": false,
    "autoUpdateSchemaFromUrl": true
  }
}
```

I then get the response in studio of (truncated to just head to show 404)
```json
{
  "errors": [
    {
      "message": "404: Not Found",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "response": {
          "url": "http://localhost:4003/",
          "status": 404,
          "statusText": "Not Found",
```

I can't seem to be able to have the other subgraphs mocked and then use a local version of another subgraph with a path in it's URL even though there are examples like this where the docs showing using the GitHub graphql url (ref: https://www.apollographql.com/docs/federation/v2/workbench/mocking/)

**Comment by michael-watson** [comment]
@damienpontifex If you open the "Output" panel in VS Code, the dropdown has an "Apollo Workbench" option that should give more information of what is going on. Can you send a screenshot of what you're seeing there and I might be able to dig deeper? I just tried on the latest version and didn't have issues on my end, so it might be helpful to have the workbench file if you're still seeing the issue (email: watson@apollographql.com)

It looks like the server isn't accessible for some reason, I'm assuming you have `http://localhost:4003/` running locally on your machine?

**Comment by barrynorman** [comment]
Same here. I set my config as below, but as soon as I start it, the URL is overwritten with a local url.
Any ideas?

```
{
  "url": "https://subgraph.example.com/graphql",
  "requiredHeaders": [],
  "mocks": {
    "shouldMock": false,
    "autoUpdateSchemaFromUrl": false
  }
}
```

**Comment by michael-watson** [comment]
Workbench now uses the format of the [supergraph config file](https://www.apollographql.com/docs/rover/commands/supergraphs#yaml-configuration-file) and [`rover dev`](https://www.apollographql.com/docs/rover/commands/dev). The new configuration file should work when `subgraph.schema.workbench_design` is populated pointing at a local schema file. We will add some additional mocking commands to make that experience better, currently you can write click a subgraph and set it to mock that way.
