### ISSUE TITLE
Bug: not able to run the command [>Apollo Workbench: Start Mocked Servers]

### ISSUE THREAD

**Issue by sepsol** [apollographql/apollo-workbench-vscode#79]
Hi @michael-watson, thanks for the great extension! I was giving this extension a try and followed along with [one of your videos](https://youtu.be/2up1nWkquSI) from back in January. I am trying to run the Mock Server but I'm not able to see the command in my VS Code.

![image](https://user-images.githubusercontent.com/47871887/114055556-ba423a80-9845-11eb-9a18-358cd8ee11c3.png)

What I've tried so far:
* Reloading VS Code
* Restarting my computer
* Uninstalling and re-installing the extension
* Typing out the full command manually and pressing enter
* Selecting the `.apollo-workbench` file and then trying to find the command
* Selecting the `airline-graph` supergraph and then trying to find the command
* Selecting either the `accounts` or `flights` subgraph services and then trying to find the command

My system specs:
* macOS Big Sur v11.2.1
* VS Code v1.55.0
* Apollo GraphQL Extension v1.18.2
* Apollo Workbench Extension v1.0.11

**Comment by sepsol** [comment]
Also I didn't know if this worths an issue of its own but I've noticed that the latest release in this repo is v1.0.12 but on VS Code Marketplace I was able to download v1.0.11. I couldn't find the `.vsix` file for v1.0.12 from your repo to give that one a try.

**Comment by michael-watson** [comment]
@sepsol I see what you're saying, I don't think I'm exposing the command in that way anymore and there is now a play button next to the 

![Screen Shot 2021-04-12 at 7 44 31 AM](https://user-images.githubusercontent.com/8645958/114413563-f2f25480-9b62-11eb-8e6e-918b0f6051d9.png)

I think it makes sense to re-expose this command though and get that in the next build. I also didn't notice the version difference, that is from how I manually publish the extension. This is all due to a github action I use to auto-bump the version after merging to master.

**Comment by saadsaifse** [comment]
For me the `Start Supergraph Mocks` gives the following error 
```
Command 'Start Supergraph Mocks' resulted in an error (Running the contributed command: 'local-supergraph-designs.startMocks' failed.)
```
When starting from the Play button as mentioned above, all sub-graphs and gateways fire up and I can see the playgrounds in the browser. However the ExecuteQuery commands do not return any mock data or anything inside the VSCode. Its just shows a blank screen on the right side.

**Comment by michael-watson** [comment]
@sepsol I just pushed a change into a branch that will get us a new build. It should fix the behavior around *Start Supergraph Mocks* where it shows a quick pick option list of the loaded workbench files. A new release should pop up shortly and I'll test that out, if good, we can push that into the marketplace

@saadsaifse thanks for the note, as for the ExecuteQuery Command issue you mentioned, can you provide some more clarity here? Workbench won't actually execute any query (although it certainly could and I would welcome that feature request as a new issue), it can only generate the query plan. Let me know if you're seeing something I'm missing, I am just returning today after summit last week. 

![Screen Shot 2021-04-12 at 8 43 14 AM](https://user-images.githubusercontent.com/8645958/114422536-39e44800-9b6b-11eb-9d4c-38690703bb3e.png)

**Comment by saadsaifse** [comment]
@michael-watson thank you for your prompt response.
I see! the queries are executed in the Playground where I got the mocked data (so cool! thanks for that)
My VSCode shows me the `Execute Query` option right on top of that query (see image below). When I click that, it opens a tab on the right which is blank. It might be the Apollo GraphQL extension feature but I think it would be a great addition to this extension as well.  

![image](https://user-images.githubusercontent.com/21024875/114432015-75f5c800-9bc0-11eb-8cc2-a1e73f9c8116.png)

**Comment by michael-watson** [comment]
@saadsaifse thanks for pointing this out, I didn't even test this. I opened a new issue #81 for this, should be able to investigate and figure it out. 

If you wanted a quick workaround, try adding an `apollo.config.js` to the root of the folder you  have opened and add the following:
```
module.exports = {
  client: {
    service: {
      name: 'workbench-gatgeway',
      url: 'http://localhost:5000', <- or whatever your gateway is running at 
  }
}
```

Then that execute query might work, if it does let me know.

**Comment by sepsol** [comment]
@michael-watson That play button worked just fine, thanks for your help! Looking forward to the new version.

**Comment by michael-watson** [comment]
@sepsol I will make a release this Friday, there are a lot of other things I want to clean up for that release as well. This will be included in it for sure, but I want the docs cleaned up and fix the changelog which will take a couple days on my end.

In the short term, we'll probably have a weekly release in that marketplace or something done manually. Once that is smooth and I feel comfortable, I'll setup automated publishing for this repo. It should be pretty simple with it's current state.

**Comment by sepsol** [comment]
@michael-watson Thanks for the clarification! That makes sense.

**Comment by michael-watson** [comment]
With the latest release, the mocking engine has been overhauled along with the docs. I'm going to close this issue out now that is complete
