### ISSUE TITLE
Update Workbench extension on Marketplace

### ISSUE THREAD

**Issue by Kartikkumargujarati** [apollographql/apollo-workbench-vscode#91]
The current version of the extension on the Marketplace is v1.0.11. As noted in https://github.com/apollographql/apollo-workbench-vscode/issues/90#issuecomment-851696667, there is a bug in that version that does not use the custom mock that is being provided. This is not the case on the latest version - v1.0.18 of the extension. 

Can y'all update the extension version on the marketplace so that others can download a "good" version of the extension directly from VSCode?

**Comment by michael-watson** [comment]
@Kartikkumargujarati I'll be working on having the next release be automated through the `vsce` CLI so the versions are never out of sync

**Comment by Kartikkumargujarati** [comment]
Thanks, @michael-watson. Closing this issue.
