### ISSUE TITLE
Bug: not able to run command: "Apollo Workbench: Login to Apollo"

### ISSUE THREAD

**Issue by martinmart92** [apollographql/apollo-workbench-vscode#92]
When trying to configure my Personal API Key into Visual Studio code, I follow the following sequence:
 - click on View, in the menu
 - click on Command Palette inside the View menu
 - type to search for "Apollo Workbench: Login to Apollo", click on it
 - I get an error message: "Command 'Apollo Workbench: Login to Apollo' resulted in an error (command 'extension.enterStudioApiKey' not found)"

Is there anything else to install? I'm relatively new, not sure what I'm missing 
My versions: 
- Visual Studio: Version: 1.57.1 (Universal)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z (2 wks ago)
- Extension: Apollo Workbench
apollographql.apollo-workbench `v1.0.11`
 - Extension: Apollo GraphQL
apollographql.vscode-apollo `v1.19.3`

**Comment by michael-watson** [comment]
Hi @martinmart92 , I just uploaded a new release that should have this all fixed in it. Would you be able to verify for me?

**Comment by michael-watson** [comment]
Going to close out for the time being, please re-open if you're seeing issues still!

**Comment by dchambers** [comment]
I have the same issue. This is working for me on my old laptop, but won't work given a fresh install on my new laptop. Following the original poster's instructions I too also get:

```Command 'Apollo Workbench: Login to Apollo' resulted in an error (command 'extension.enterStudioApiKey' not found)```

The last time I installed this plugin it immediately prompted me with a "No user api key was found", and let me enter you API key right there and then, but it's not doing that this time. If I look at the 'Runtime Status' for the extension it say 'Not yet activated.', and in fact I'm also getting this for the 'Apollo GraphQL' plugin too, whereas other plugins I've installed show an activation time in milliseconds.

The version of Apollo Workbench is `1.1.6`, and the version of VSCode is `1.60.0`, running on a Mac with macOS Big Sur as the OS.

Any ideas?

**Comment by dchambers** [comment]
@michael-watson, should this ticket be re-opened?

**Comment by dchambers** [comment]
@martinmart92 and I are actually both in the same company, so it sounds like it maybe something specific to our laptops that's causing this, so some advice around the sending of logs, etc may be needed.

**Comment by martinmart92** [comment]
thanks @michael-watson ! However I still reproduce the issue with the latest version. I'm happy to send logs if that can help. As @dchambers mentioned, there might be some specificity of our company laptop breaking a pre-requisite. 

When I do cmd+shift+p and choose "Apollo Workbench: login to Apollo" I get the same error message: 
```Command 'Apollo Workbench: Login to Apollo' resulted in an error (command 'extension.enterStudioApiKey' not found)```


Here's my "About Visual Studio code" info:

```
Version: 1.62.3 (Universal)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T07:59:13.865Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

**Comment by martinmart92** [comment]
in the Console of the Developer Tools, I got:


```
Error: Unable to read file '/Users/martin.coste/.vscode/extensions/apollographql.vscode-apollo-1.19.9/graphql.configuration.json' (Error: Unable to resolve nonexistent file '/Users/martin.coste/.vscode/extensions/apollographql.vscode-apollo-1.19.9/graphql.configuration.json')
    at yi.doReadFileStream (workbench.desktop.main.js:602)
    at async yi.doReadFile (workbench.desktop.main.js:602)
    at async M.readExtensionResource (workbench.desktop.main.js:1498)
(anonymous) @ workbench.desktop.main.js:1737
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout
```
